CREATE TABLE TUMCCA_USERS (
  ID            BIGINT PRIMARY KEY    AUTO_INCREMENT,
  EMAIL         VARCHAR(32),
  MOBILE        VARCHAR(32),
  PASSWORD_HASH VARCHAR(128) NOT NULL,
  STATUS        INT          NOT NULL DEFAULT 0,
  CREATE_TIME   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_TUMCCA_USERS_EMAIL ON TUMCCA_USERS (EMAIL);
CREATE UNIQUE INDEX UQ_TUMCCA_USERS_MOBILE ON TUMCCA_USERS (MOBILE);
CREATE INDEX IX_TUMCCA_USERS_STATUS ON TUMCCA_USERS (STATUS);

CREATE TABLE TUMCCA_ROLES (
  UID       BIGINT PRIMARY KEY, -- related to TUMCCA_USERS.ID
  AUTHORITY VARCHAR(32) NOT NULL
);

CREATE TABLE TUMCCA_SESSIONS (
  TOKEN         VARCHAR(128) PRIMARY KEY,
  UID           BIGINT    NOT NULL, -- related to TUMCCA_USERS.ID
  SIGN_IN_TIME  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SIGN_OUT_TIME TIMESTAMP,
  STATUS        INT       NOT NULL DEFAULT 0
);

CREATE INDEX IX_TUMCCA_SESSIONS_UID ON TUMCCA_SESSIONS (UID);

CREATE TABLE TUMCCA_PICTURES (
  ID          BIGINT PRIMARY KEY    AUTO_INCREMENT,
  NAME        VARCHAR(64)  NOT NULL,
  BUCKET_NAME VARCHAR(128) NOT NULL,
  OSS_KEY     VARCHAR(128) NOT NULL,
  SOURCE      VARCHAR(32)  NOT NULL, -- something like avatar, works picture
  STATUS      INT          NOT NULL DEFAULT 0, -- 0: normal, 1: trash
  WIDTH       INT          NOT NULL, -- original width  add by neil 6/29/2015
  HEIGHT      INT          NOT NULL, -- original height add by neil 6/29/2015
  CREATE_TIME TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_TUMCCA_PICTURES_SOURCE ON TUMCCA_PICTURES (SOURCE);

CREATE TABLE TUMCCA_ARTISTS (
  UID          BIGINT PRIMARY KEY, -- related to TUMCCA_USERS.ID
  PSEUDONYM    VARCHAR(32)   NOT NULL,
  GENDER       INT           NOT NULL DEFAULT 0,
  INTRODUCTION VARCHAR(1024),
  TITLE        VARCHAR(64)   NOT NULL,
  HOBBIES      VARCHAR(128),
  FORTE        VARCHAR(64),
  AVATAR       BIGINT, -- related to TUMCCA_PICTURES.ID
  COUNTRY      VARCHAR(32),
  PROVINCE     VARCHAR(32),
  CITY         VARCHAR(32)
);

CREATE TABLE TUMCCA_OAUTH_USERS (
  UID         BIGINT PRIMARY KEY, -- related to TUMCCA_ARTISTS.UID
  PROVIDER    ENUM('WECHAT', 'WEIBO', 'QQ') NOT NULL,
  OPEN_ID     VARCHAR(128)                  NOT NULL,
  EMAIL       VARCHAR(32),
  MOBILE      VARCHAR(32),
  STATUS      INT                           NOT NULL DEFAULT 0,
  CREATE_TIME TIMESTAMP                     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TUMCCA_FOLLOW (
  FOLLOWER  BIGINT NOT NULL, -- related to TUMCCA_ARTISTS.UID
  TO_FOLLOW BIGINT NOT NULL, -- related to TUMCCA_ARTISTS.UID
  --2015/07/05 add by Neil
  CREATE_TIME TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  --
  PRIMARY KEY (FOLLOWER, TO_FOLLOW)
);

--2015/07/05 add by Neil
CREATE TABLE TUMCCA_FOLLOW_CATEGORY (
  FOLLOWER  BIGINT NOT NULL, -- related to TUMCCA_ARTISTS.UID
  CATEGORY  BIGINT NOT NULL, -- related to TUMCCA_WORKS_CATEGORIES.ID
  CREATE_TIME TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (FOLLOWER, CATEGORY)
);
--

CREATE TABLE TUMCCA_WORKS (
  ID          BIGINT PRIMARY KEY    AUTO_INCREMENT,
  CATEGORY    BIGINT       NOT NULL, -- related to TUMCCA_WORKS_CATEGORIES.ID
  AUTHOR      BIGINT       NOT NULL, -- related to TUMCCA_ARTISTS.UID
  STATUS      INT          NOT NULL DEFAULT 0, -- 1: available, 0: trash
  --Add by Neil. 2015/06/27
  ALBUMID     BIGINT       NOT NULL DEFAULT 0, -- 0: represent a default album(doesn't exist actually).
  TITLE       VARCHAR(64),
  DESCRIPTION VARCHAR(1024),
  TAGS        VARCHAR(1024),
  CREATE_TIME TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_TUMCCA_WORKS_CATEGORY ON TUMCCA_WORKS (CATEGORY);
CREATE INDEX IX_TUMCCA_WORKS_AUTHOR ON TUMCCA_WORKS (AUTHOR);
CREATE INDEX IX_TUMCCA_WORKS_STATUS ON TUMCCA_WORKS (STATUS);
CREATE INDEX IX_TUMCCA_WORKS_CREATE_TIME ON TUMCCA_WORKS (CREATE_TIME);
CREATE INDEX IX_TUMCCA_WORKS_ALBUMID ON TUMCCA_WORKS (ALBUMID);

CREATE TABLE TUMCCA_WORKS_PICTURES (
  WORKS   BIGINT NOT NULL, -- related to TUMCCA_WORKS.ID
  PICTURE BIGINT NOT NULL -- related to TUMCCA_PICTURES.ID
);

CREATE INDEX IX_TUMCCA_WORKS_PICTURES_WORKS ON TUMCCA_WORKS_PICTURES (WORKS);
CREATE INDEX IX_TUMCCA_WORKS_PICTURES_PICTURE ON TUMCCA_WORKS_PICTURES (PICTURE);

CREATE TABLE TUMCCA_LIKE (
  WORKS       BIGINT    NOT NULL, -- related to TUMCCA_WORKS.ID
  ADMIRER     BIGINT    NOT NULL, -- related to TUMCCA_ARTISTS.UID
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_TUMCCA_LIKE_WORKS ON TUMCCA_LIKE (WORKS);
CREATE INDEX IX_TUMCCA_LIKE_ADMIRER ON TUMCCA_LIKE (ADMIRER);
--2015/07/05 add by Neil
CREATE UNIQUE INDEX UQ_TUMCCA_LIKE_WORKS_ADMIRER ON TUMCCA_LIKE (WORKS, ADMIRER);
--

--2015/07/05 add by Neil
CREATE TABLE TUMCCA_LIKE_ALBUM (
  ALBUM       BIGINT    NOT NULL, -- related to TUMCCA_ALBUM.ID
  ADMIRER     BIGINT    NOT NULL, -- related to TUMCCA_ARTISTS.UID
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_TUMCCA_LIKE_ALBUM_ALBUM ON TUMCCA_LIKE_ALBUM (ALBUM);
CREATE INDEX IX_TUMCCA_LIKE_ALBUM_ADMIRER ON TUMCCA_LIKE_ALBUM (ADMIRER);
CREATE UNIQUE INDEX UQ_TUMCCA_LIKE_ALBUM_ALBUM_ADMIRER ON TUMCCA_LIKE_ALBUM (ALBUM, ADMIRER);
--

CREATE TABLE TUMCCA_COMMENT (
  ID          BIGINT PRIMARY KEY   AUTO_INCREMENT,
  WORKS       BIGINT        NOT NULL, -- related to TUMCCA_WORKS.ID
  REVIEWER    BIGINT        NOT NULL, -- related to TUMCCA_ARTISTS.UID
  REPLY_TARGET BIGINT NOT NULL DEFAULT 0, -- related to TUMCCA_COMMENT.ID, 0 represents the comment is not a reply.
  DESCRIPTION VARCHAR(1024) NOT NULL,
  CREATE_TIME TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_TUMCCA_COMMENT_WORKS ON TUMCCA_COMMENT (WORKS);
CREATE INDEX IX_TUMCCA_COMMENT_REVIEWER ON TUMCCA_COMMENT (REVIEWER);

CREATE TABLE TUMCCA_COLLECT (
  WORKS       BIGINT    NOT NULL, -- related to TUMCCA_WORKS.ID
  COLLECTOR   BIGINT    NOT NULL, -- related to TUMCCA_ARTISTS.UID
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_TUMCCA_COLLECT_WORKS ON TUMCCA_COLLECT (WORKS);
CREATE INDEX IX_TUMCCA_COLLECT_COLLECTOR ON TUMCCA_COLLECT (COLLECTOR);
--2015/07/05 add by Neil
CREATE UNIQUE INDEX UQ_TUMCCA_COLLECT_WORKS_COLLECTOR ON TUMCCA_COLLECT (WORKS, COLLECTOR);
--

--2015/07/05 add by Neil
CREATE TABLE TUMCCA_COLLECT_ALBUM (
  ALBUM       BIGINT    NOT NULL, -- related to TUMCCA_ALBUM.ID
  COLLECTOR   BIGINT    NOT NULL, -- related to TUMCCA_ARTISTS.UID
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_TUMCCA_COLLECT_ALBUM_ALBUM ON TUMCCA_COLLECT_ALBUM (ALBUM);
CREATE INDEX IX_TUMCCA_COLLECT_ALBUM_COLLECTOR ON TUMCCA_COLLECT_ALBUM (COLLECTOR);
CREATE UNIQUE INDEX UQ_TUMCCA_COLLECT_ALBUM_ALBUM_COLLECTOR ON TUMCCA_COLLECT_ALBUM (ALBUM, COLLECTOR);
--

CREATE TABLE TUMCCA_PICTURES_CACHE (
  URI          VARCHAR(64) PRIMARY KEY, -- something like /api/pictures/download/1
  STORAGE_NAME VARCHAR(128) NOT NULL,
  CREATE_TIME  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IX_TUMCCA_PICTURES_CACHE_CREATE_TIME ON TUMCCA_PICTURES_CACHE (CREATE_TIME);

CREATE TABLE TUMCCA_ERRORS (
  CODE    INT PRIMARY KEY,
  MESSAGE VARCHAR(128) NOT NULL
);

CREATE TABLE TUMCCA_ANDROID_LOGS (
  ID          BIGINT PRIMARY KEY     AUTO_INCREMENT,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  TS          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TUMCCA_WORKS_CATEGORIES (
  ID   BIGINT PRIMARY KEY     AUTO_INCREMENT,
  PATH VARCHAR(128) NOT NULL  DEFAULT '/', -- something like /2/7/89/, the number relates to TUMCCA_WORKS_CATEGORIES.ID
  NAME VARCHAR(32)  NOT NULL
);

CREATE UNIQUE INDEX UQ_TUMCCA_WORKS_CATEGORIES_PATH_NAME ON TUMCCA_WORKS_CATEGORIES (PATH, NAME);

CREATE TABLE TUMCCA_SERVER_CLUSTERS (
  SERVER_ID     VARCHAR(64) PRIMARY KEY,
  STATUS        INT       NOT NULL DEFAULT 0, -- 1: ON, 0: OFF
  STARTUP_TIME  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SHUTDOWN_TIME TIMESTAMP NOT NULL
);

CREATE TABLE TUMCCA_WORKS_TAGS (
  ID   BIGINT PRIMARY KEY     AUTO_INCREMENT,
  NAME VARCHAR(32) NOT NULL
);

CREATE UNIQUE INDEX UQ_TUMCCA_WORKS_TAGS_NAME ON TUMCCA_WORKS_TAGS (NAME);

CREATE TABLE TUMCCA_USER_NOTIFICATIONS (
  ID          BIGINT PRIMARY KEY     AUTO_INCREMENT,
  UID         BIGINT        NOT NULL,
  ACTION      VARCHAR(32)   NOT NULL,
  MESSAGE     VARCHAR(1024) NOT NULL,
  STATUS      INT           NOT NULL DEFAULT 0, -- 0: Pending; 1: Notified
  CREATE_TIME TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  READ_TIME   TIMESTAMP
);

CREATE INDEX IX_TUMCCA_USER_NOTIFICATIONS_UID ON TUMCCA_USER_NOTIFICATIONS (UID);
CREATE INDEX IX_TUMCCA_USER_NOTIFICATIONS_STATUS ON TUMCCA_USER_NOTIFICATIONS (STATUS);

--Add by Neil. 2015/06/27
CREATE TABLE TUMCCA_ALBUM (
  ID          BIGINT PRIMARY KEY   AUTO_INCREMENT,
  AUTHOR      BIGINT        NOT NULL, -- related to TUMCCA_ARTISTS.UID
  TITLE       VARCHAR(64)   NOT NULL,
  DESCRIPTION VARCHAR(1024),
  CREATE_TIME TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_TUMCCA_ALBUM_AUTHOR ON TUMCCA_ALBUM (AUTHOR);